# Uncomment the next line to define a global platform for your project

platform :ios, '10.0'

def shared_pods
  pod 'R.swift', '~> 3.3'
  pod 'Kingfisher', '~> 4.1'
  pod 'IQKeyboardManagerSwift', '~> 5.0'
  pod 'PKHUD', '~> 5.0'
  pod 'Alamofire', '~> 4.5'
  pod 'PromiseKit/Alamofire', '~> 4.5'
end

target 'shoppingIOS' do
  use_frameworks!
  shared_pods
end

target 'shoppingIOSTests' do
  inherit! :search_paths
  # Pods for testing
end

target 'shoppingIOSUITests' do
  inherit! :search_paths
  # Pods for testing
end


